### ISSUE TITLE
 best react app ever!

### ISSUE THREAD

**Issue by new-b** [sasssssha/wearshop#1]
I mean it

**Comment by sasssssha** [comment]
very funny

**Comment by new-b** [comment]
Are you retarted? What's the point in changing title?

**Comment by sasssssha** [comment]
no i can't

**Comment by new-b** [comment]
Fucking retard

**Comment by sasssssha** [comment]
no

**Comment by new-b** [comment]
![biohkw8cqaedljh](https://user-images.githubusercontent.com/26943089/31857624-9263a9d4-b6eb-11e7-87a4-c6b03995ef1e.jpg)

**Comment by new-b** [comment]
Axxaxaxaxaxa

**Comment by new-b** [comment]
SOOOOQA
